# Exported from Render on 2026-08-18T21:42:33Z
version: "1"
services:
- type: web
  name: mikrotik-voucher-app
  runtime: docker
  repo: https://github.com/radwanalashram/Mikrotik-Voucher-App
  plan: free
  envVars:
  - key: MIKROTIK_PORT
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USERNAME
    sync: false
  - key: DB_DATABASE
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_CONNECTION
    sync: false
  - key: APP_KEY
    sync: false
  - key: APP_DEBUG
    sync: false
  - key: APP_ENV
    sync: false
  - key: APP_NAME
    sync: false
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
